// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {device} from '../models';

export function DetectPartitions(arg1:string):Promise<Array<main.PartitionDTO>>;

export function ListDevices():Promise<Array<device.Device>>;

export function OpenFullDiskAccessSettings():Promise<void>;

export function Preview(arg1:string,arg2:string):Promise<main.PreviewDTO>;

export function Recover(arg1:string,arg2:Array<string>,arg3:string,arg4:boolean):Promise<main.RecoverDTO>;

export function RevealInFinder(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectImageFile():Promise<string>;

export function SelectSaveImagePath(arg1:string):Promise<string>;

export function StartClone(arg1:string,arg2:string):Promise<void>;

export function StartScan(arg1:string,arg2:Array<string>,arg3:boolean,arg4:Array<string>,arg5:Array<number>):Promise<void>;

export function StartScanDevice(arg1:string,arg2:Array<string>,arg3:boolean,arg4:Array<string>,arg5:Array<number>):Promise<void>;

export function SupportedRawTypes():Promise<Array<string>>;
