// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelClone() {
  return window['go']['main']['App']['CancelClone']();
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function DetectPartitions(arg1) {
  return window['go']['main']['App']['DetectPartitions'](arg1);
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function OpenFullDiskAccessSettings() {
  return window['go']['main']['App']['OpenFullDiskAccessSettings']();
}

export function Preview(arg1, arg2) {
  return window['go']['main']['App']['Preview'](arg1, arg2);
}

export function Recover(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Recover'](arg1, arg2, arg3, arg4);
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}

export function SelectSaveImagePath(arg1) {
  return window['go']['main']['App']['SelectSaveImagePath'](arg1);
}

export function StartClone(arg1, arg2) {
  return window['go']['main']['App']['StartClone'](arg1, arg2);
}

export function StartScan(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartScan'](arg1, arg2, arg3, arg4, arg5);
}

export function StartScanDevice(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartScanDevice'](arg1, arg2, arg3, arg4, arg5);
}

export function SupportedRawTypes() {
  return window['go']['main']['App']['SupportedRawTypes']();
}
